---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microbot
  name: microbot
  namespace: bot-demo
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: microbot
  template:
    metadata:
      labels:
        app: microbot
    spec:
      containers:
      - name: microbot
        image: dontrebootme/microbot:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microbot-v2
  name: microbot-v2
  namespace: bot-demo
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: microbot-v2
  template:
    metadata:
      labels:
        app: microbot-v2
    spec:
      containers:
      - name: microbot-v2
        image: dontrebootme/microbot:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microbot-svc
  namespace: bot-demo
spec:
  selector:
    app: microbot
  ports:
  - port: 9100
    targetPort: 80
    appProtocol: https
---
apiVersion: v1
kind: Service
metadata:
  name: microbot-svc-v2
  namespace: bot-demo
spec:
  selector:
    app: microbot-v2
  ports:
  - port: 9200
    targetPort: 80
    appProtocol: https
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: microbot-route
  namespace: bot-demo
spec:
  parentRefs:
  - name: istio
    namespace: gateway
  hostnames: ["microbot.bebr.live"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: microbot-svc
      port: 9100
      weight: 50
    - name: microbot-svc-v2
      port: 9200
      weight: 50