---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: httpbin
  name: apiv2
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: apiv2
  template:
    metadata:
      labels:
        app: apiv2
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: apiv2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apiv2
  namespace: httpbin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: apiv2
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: apiv2
  namespace: httpbin
spec:
  parentRefs:
  - name: istio
    namespace: gateway
  hostnames: ["httpbin.bebr.live"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: apiv2
      port: 8080