apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: observability
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - prometheus.bebr.live
      secretName: prometheus-ingress-tls
  rules:
    - host: prometheus.bebr.live
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kube-prom-stack-kube-prome-prometheus
                port:
                  number: 9090
